import logging
import os
import subprocess
import sys
import xml.etree.ElementTree as ET
from typing import Dict, List

from .m3u_parser import M3UChannel
from .mxf import _build_channel_metadata, _collect_programmes
from .xmltv import resolve_channel_xmltv_ids

logger = logging.getLogger(__name__)


def write_vista_guide_xml(
    xmltv_xml: str,
    lineup: List[Dict],
    channel_map: Dict[str, M3UChannel],
    output_path: str,
) -> str:
    xmltv_ids = resolve_channel_xmltv_ids(xmltv_xml, channel_map) if xmltv_xml else {}
    channel_meta = _build_channel_metadata(lineup, channel_map, xmltv_ids)
    service_programmes = _collect_programmes(xmltv_xml, channel_meta)

    root = ET.Element("epg_data", {
        "supplier": "HDHRProxy",
        "supplier_info": "HDHRProxy XMLTV bridge",
        "language": "en",
        "file_version": "1",
        "schema_version": "1.0",
        "supplierId": "HDHRProxy",
        "headendId": "HDHRProxy",
        "headend_name": "HDHRProxy",
    })
    ET.SubElement(root, "copyright").text = "Generated by HDHRProxy"

    sorted_meta = sorted(channel_meta.values(), key=lambda item: (item["major"], item["minor"]))
    if not sorted_meta:
        raise ValueError("Vista guide import requires at least one scanned channel.")
    tune_requests = ET.SubElement(root, "tuneRequests", {"ct": str(len(sorted_meta))})
    service_offsets = {}
    for offset, meta in enumerate(sorted_meta):
        service_offsets[meta["service_id"]] = offset
        tune_request = ET.SubElement(tune_requests, "tr", {
            "type": "trATSCType",
            "number": str(_vista_virtual_channel_number(meta["major"], meta["minor"])),
            "major": str(meta["major"]),
            "minor": str(meta["minor"]),
            "physical": str(meta["physical_channel"]),
        })
        ET.SubElement(tune_request, "s", {
            "name": meta["service_name"],
            "call_sign": meta["call_sign"],
            "id": meta["xmltv_id"],
            "virtualchannelnumber": str(_vista_virtual_channel_number(meta["major"], meta["minor"])),
            "GuideService": "1",
        })

    ET.SubElement(root, "categories")
    ET.SubElement(root, "programAttributes")
    ET.SubElement(root, "programRatingAttributes")
    ET.SubElement(root, "scheduleEntryAttributes")

    programs = ET.SubElement(root, "programs")
    program_indexes = {}
    next_program_index = 0
    for service_id in sorted(service_programmes):
        for program in service_programmes[service_id]:
            key = _vista_program_key(program)
            if key in program_indexes:
                continue
            program_indexes[key] = next_program_index
            next_program_index += 1
            attrs = {
                "i": program["uid"],
                "t": program["title"],
                "l": "en",
            }
            if program.get("description"):
                attrs["d"] = program["description"]
            if program.get("episode_title"):
                attrs["e"] = program["episode_title"]
            if program.get("year"):
                attrs["y"] = str(program["year"])
            if program.get("airdate"):
                attrs["od"] = str(program["airdate"])
            if program.get("is_series"):
                attrs["k"] = "1"
            ET.SubElement(programs, "p", attrs)
    programs.set("ct", str(next_program_index))
    if next_program_index <= 0:
        raise ValueError("Vista guide import requires at least one XMLTV programme.")

    schedule_entries = ET.SubElement(root, "scheduleEntries")
    for service_id in sorted(service_programmes):
        offset = service_offsets.get(service_id)
        if offset is None:
            continue
        for program in service_programmes[service_id]:
            airing = ET.SubElement(schedule_entries, "ses", {
                "ct": "1",
                "io": str(offset),
                "start": _vista_datetime(program["start_time"]),
            })
            ET.SubElement(airing, "se", {
                "p": str(program_indexes[_vista_program_key(program)]),
                "d": str(program["duration"]),
            })
    ET.SubElement(root, "scheduleEntries2")

    output_path = os.path.abspath(output_path)
    ET.ElementTree(root).write(output_path, encoding="utf-8", xml_declaration=True)
    logger.info(
        "Wrote Vista ehepg guide XML (%s services, %s programs): %s",
        len(sorted_meta),
        next_program_index,
        output_path,
    )
    return output_path


def import_vista_guide_xml(output_path: str) -> None:
    helper = _find_vista_import_helper()
    log_path = os.path.join(os.path.dirname(os.path.abspath(sys.argv[0])), "vista_guide_import.log")
    logger.info("Importing Vista ehepg guide XML: %s", output_path)
    subprocess.run([helper, os.path.abspath(output_path), log_path], check=True)


def validate_vista_guide_xml(output_path: str) -> None:
    subprocess.run([_find_vista_import_helper(), "--validate", os.path.abspath(output_path)], check=True)


def _find_vista_import_helper() -> str:
    candidates = []
    bundle_dir = getattr(sys, "_MEIPASS", None)
    if bundle_dir:
        candidates.append(os.path.join(bundle_dir, "HDHRProxyWMC-VistaGuideImport.exe"))
    candidates.extend([
        os.path.join(os.path.dirname(os.path.abspath(sys.argv[0])), "HDHRProxyWMC-VistaGuideImport.exe"),
        os.path.join(os.path.dirname(os.path.dirname(__file__)), "vista_helper", "bin", "HDHRProxyWMC-VistaGuideImport.exe"),
    ])
    for candidate in candidates:
        if os.path.exists(candidate):
            return candidate
    raise FileNotFoundError("Vista guide import helper was not packaged with the program.")


def _vista_virtual_channel_number(major: int, minor: int) -> int:
    return major if minor <= 0 else major * 1000 + minor


def _vista_program_key(program: Dict) -> str:
    return program["uid"]


def _vista_datetime(value: str) -> str:
    return value.replace(".000Z", "")
